In [1]:
###Session 5

#Arrays
#basic python libraries
#numerical python
#datatype of NumPy = Arrays
#In Python we import multiple libraries to make our work easy , as if try to make functions over and over that would cost us time
#A Simple way out here is to import libraries i.e import matplotlib and generate graphs like bar and line charts

In [2]:
list_1 = [1,2,3,4,5]

In [3]:
type(list_1)

list

In [4]:
import numpy as np #np is nickname of numpy

In [5]:
import pandas as pd #pd is nickname of pandas

In [6]:
import matplotlib as mt #mt is nickname of matplotlib

In [7]:
list1_array = np.array(list_1)

In [13]:
# You need to convert data into numpy array
# numpy array is a data type specifically for numpy library
# numpy array is a basic data type

In [8]:
list1_array

array([1, 2, 3, 4, 5])

In [9]:
array_3 = np.array([2,4,6])

In [10]:
array_3

array([2, 4, 6])

In [11]:
#One Dimentional Array
one_dim_array = np.array([1,2,3,4,5])


In [12]:
one_dim_array

array([1, 2, 3, 4, 5])

In [13]:
one_dim_array.shape

(5,)

In [14]:
one_dim_array.size

5

In [28]:
#two dimentional array 

In [15]:
two_dim_array = np.array([[1,2,3,4],[2,4,6,8]])

In [16]:
two_dim_array

array([[1, 2, 3, 4],
       [2, 4, 6, 8]])

In [17]:
two_dim_array.shape
# 2 rows 4 columns

(2, 4)

In [18]:
two_dim_array.size
# 2*4

8

In [19]:
one_dim_array.ndim

1

In [20]:
two_dim_array.ndim

2

In [41]:
###Arange

In [22]:
array_abc = np.arange(1,100,2)

# 1st value = staring value
# 2nd value = ending  value + 1
# 3rd value = number of gaps

In [23]:
array_abc

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [26]:
odm_array = np.array([1,2,3,4,5])
tdm_array = np.array([[1,2,3],[5,6,7]])

In [28]:
odm_array

array([1, 2, 3, 4, 5])

In [30]:
tdm_array

array([[1, 2, 3],
       [5, 6, 7]])

In [32]:
tdm_array.ndim
# number of dimensions

2

In [34]:
odm_array.ndim

1

In [36]:
array_abc = np.arange(1,100,2)

In [38]:
array_abc

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [40]:
array_bcg = np.arange(5,10000,100)

In [41]:
#Linspace

In [42]:
#First element = Starting
#Second element =Last Element
#Third Element = Number of elements you want to divide into equally spaced

In [44]:
line_a = np.linspace(10,30,6)

In [45]:
#Arithmatic Operations

In [46]:
a = [1,5,7,8,13,20]
b = [1,2,3,4,5,6]

In [48]:
a_array = np.array(a)
b_array = np.array(b)

In [50]:
a_array , b_array

(array([ 1,  5,  7,  8, 13, 20]), array([1, 2, 3, 4, 5, 6]))

In [52]:
np.add(a_array,b_array)

array([ 2,  7, 10, 12, 18, 26])

In [55]:
np.multiply(a_array,b_array)

array([  1,  10,  21,  32,  65, 120])

In [57]:
np.divide(a_array,b_array)

array([1.        , 2.5       , 2.33333333, 2.        , 2.6       ,
       3.33333333])

In [59]:
np.std(a_array)

6.082762530298219

In [61]:
np.var(a_array)

37.0

In [63]:
np.median(a_array)

7.5

In [65]:
np.sin(a_array)

array([ 0.84147098, -0.95892427,  0.6569866 ,  0.98935825,  0.42016704,
        0.91294525])

In [67]:
np.tan(a_array)

array([ 1.55740772, -3.38051501,  0.87144798, -6.79971146,  0.46302113,
        2.23716094])

In [68]:
np.log(a_array)

array([0.        , 1.60943791, 1.94591015, 2.07944154, 2.56494936,
       2.99573227])